
package paqueteServicio;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Antiguedad", targetNamespace = "http://paqueteServicio/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Antiguedad {


    /**
     * 
     * @param fechaContrato
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "Antiguedad")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Antiguedad", targetNamespace = "http://paqueteServicio/", className = "paqueteServicio.Antiguedad_Type")
    @ResponseWrapper(localName = "AntiguedadResponse", targetNamespace = "http://paqueteServicio/", className = "paqueteServicio.AntiguedadResponse")
    @Action(input = "http://paqueteServicio/Antiguedad/AntiguedadRequest", output = "http://paqueteServicio/Antiguedad/AntiguedadResponse")
    public Integer antiguedad(
        @WebParam(name = "fechaContrato", targetNamespace = "")
        String fechaContrato);

    /**
     * 
     * @param numero1
     * @param numero2
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "operation", targetNamespace = "http://paqueteServicio/", className = "paqueteServicio.Operation")
    @ResponseWrapper(localName = "operationResponse", targetNamespace = "http://paqueteServicio/", className = "paqueteServicio.OperationResponse")
    @Action(input = "http://paqueteServicio/Antiguedad/operationRequest", output = "http://paqueteServicio/Antiguedad/operationResponse")
    public Integer operation(
        @WebParam(name = "numero1", targetNamespace = "")
        int numero1,
        @WebParam(name = "numero2", targetNamespace = "")
        int numero2);

}
