/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Modelo.DAO.UsuarioDAO;  //PAQUETE ModeloDAO
import Modelo.DTO.Usuario; //PAQUETE ModeloDTO
import com.placeholder.PlaceHolder; //LIBRERIA PLACEHOLDER PARA JAVA JFRAME
import java.awt.Dimension;
import java.util.ArrayList; //PAQUUETE PARA LOS ARRAY LIST
import javax.swing.ImageIcon; //PAQUETE PARA USAR LAS IMAGENES
import javax.swing.JOptionPane; //PAQUETE PARA VENTANAS EMERGENTES

/**
 *
 * @author Angelo
 */
public class Iniciar_Sesion extends javax.swing.JFrame {

    /**
     * Creates new form Iniciar_Sesion
     */
    private int rut; //VARIABLE PARA RESCATAR EL RUT DEL USUARIO
    private String pass; //VARIABLE PARA RESCATAR CONTRASEÑA DEL USUARIO
    public static String nombre; //VARIABLE PARA RESCATAR NOMBRE DEL USUARIO
                                 //ES ESTATICA, PUESTO QUE LA NECESITO PARA OTRA VENTANA
    
    public Iniciar_Sesion() {
        initComponents();
        this.setMinimumSize(new Dimension(550, 200)); 
        PlaceHolder holder = new PlaceHolder(txtUsua, "Sin CV"); //PARA AÑADIR UN PLACEHOLDER
        setIconImage(new ImageIcon(getClass().getResource("/Imagen/LogoSGP.PNG")).getImage()); //ESTABLECER ICONO DEL SW
        btnIngresar.requestFocusInWindow(); //PARA HACER FOCUS AL BOTON "INGRESAR"
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsua = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtContra = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administración Gestión Permiso ");
        setSize(new java.awt.Dimension(1280, 720));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel1.setText("R.U.N:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel2.setText("Contraseña:");

        txtUsua.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txtUsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuaActionPerformed(evt);
            }
        });
        txtUsua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuaKeyTyped(evt);
            }
        });

        btnIngresar.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/login-16.png"))); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        btnIngresar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnIngresarKeyPressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/LogoSGP.PNG"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel4.setText("*");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel5.setText("*");

        txtContra.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUsua, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(btnIngresar)
                    .addComponent(txtContra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtUsua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel5))
                            .addComponent(txtContra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnIngresar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuaActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
    try
    {
        if(txtUsua.getText().isEmpty()) //VALIDA SI EL txtUsua esta vacio
        {
             JOptionPane.showMessageDialog(null,"Ingrese Rut"); //GATILLA MENSAJE DE ERROR
             txtUsua.requestFocus(); //LA APLICACION FOCUSEA EL CAMPO DE ENTRADA
             throw new Exception(); //SE EJECUTA UNA EXCEPCION, POR ENDE SE DETIENE EN ESTE PUNTO
        }
        if(txtUsua.getText().length()>=11) //VALIDA SI EL txtUsua es mayor a 11 caracteres
        {
            JOptionPane.showMessageDialog(null,"Ingrese Un Rut Valido (Sin CV)"); //GATILLA MENSAJE DE ERROR
            txtUsua.requestFocus(); //LA APLICACION FOCUSEA EL CAMPO DE ENTRADA
            throw new Exception(); //SE EJECUTA UNA EXCEPCION, POR ENDE SE DETIENEN EN ESTE PUNTO
        }
        if(String.valueOf(txtContra.getPassword()).length()==0) //VALIDA SI EL txtContra esta vacia
        {
            JOptionPane.showMessageDialog(null,"Ingrese Contraseña"); //GATILLA MENSAJE DE ERROR
            txtContra.requestFocus(); //LA APLICACION FOCUSEA EL CAMPO DE ENTRADA
            throw new Exception(); //SE EJECUTA UNA EXCEPCION, POR ENDE SE DETIENE EN ESTE PUNTO
        }
        rut = Integer.parseInt(txtUsua.getText()); //ASIGNAMOS LO INGRESADO EN EL txtUsua A LA VARIABLE rut
        pass = String.valueOf(txtContra.getPassword()); //ASIGNAMOS LO INGRESADO EN EL txtContra A LA VARIABLE pass
        UsuarioDAO ud = new UsuarioDAO(); //CREAMOS UN OBJETO UsuarioDAO
        ArrayList<Usuario>lista = null;  //CREAMOS UNA LISTA DE TIPO Usuario
        lista = ud.iniciar_sesion(rut,pass); //LLAMAMOS AL METODO INICIAR_SESION()
        if(lista.isEmpty()) //VALIDA SI LA LISTA ENCONTRO ALGO CON LO QUE INGRESAMOS
        {
             JOptionPane.showMessageDialog(null,"Usuario O Contraseña No Valido!!!"); //NOTIFICAMOS QUE EL USER O PASS ESTA INCORRECTO
             btnIngresar.requestFocusInWindow(); //PARA HACER FOCUS AL BOTON
        }else
        {
            nombre = lista.get(0).getNombre(); //ASIGNAMOS EL NOMBRE OBTENIDO, DE LA LISTA
            Iniciar_Sesion.this.dispose(); //CERRAMOS LA VENTANA SESION
            Menu m = new Menu(); //ABRIMOS LA VENTANA MENU
            m.setVisible(true); //HACEMOS VISIBLE LA VENTANA MENU
            
        }
        
    }catch(Exception e)
    {
        //JOptionPane.showMessageDialog(null,"Algo esta fallando");
        //ESTA LINEA SE GATILLA CUANDO INGRESO UN RUT MAYOR A 10 CARACTERES, ENTRE OTRAS COSAS, E DECIDO
        //COMENTARLO, PUESTO QUE ESTAN CONTROLADO LOS ERRORES QUE SE PUEDEN GATILLAR
    }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtUsuaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuaKeyTyped
        char car = evt.getKeyChar(); 
        if((car<'0' || car>'9')) //para validar solo numeros en txtUsua
        {
            evt.consume(); //evita ingresar lo NO DESEADO
        }
        if (txtUsua.getText().length()>=11) //Valida largo de un campo
        {
            evt.consume(); //evita ingresar lo NO DESEADO
        }
    }//GEN-LAST:event_txtUsuaKeyTyped

    private void btnIngresarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnIngresarKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) { //HABILITA CLIC AL BOTON INGRESAR CON LA TECLA "ENTER"
            btnIngresarActionPerformed(null); //PERMITE HACER CLIC CON TECLA INTRO EN EL BOTON
        }        
    }//GEN-LAST:event_btnIngresarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Iniciar_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Iniciar_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Iniciar_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Iniciar_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Iniciar_Sesion().setVisible(true);
                Iniciar_Sesion is = new Iniciar_Sesion();  //Inicia la aplicacion
                is.setLocationRelativeTo(null);  //Centra la pantalla
                is.setVisible(true); //Deja visible la pantalla
                is.setSize(500,220);  //Define el tamaño de la pantalla
                is.setResizable(false);  //Deshabilita modificar el tamaño de la pantalla
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JTextField txtUsua;
    // End of variables declaration//GEN-END:variables
}
